### PR TITLE
Typography Updates

### PR DESCRIPTION
**Pull request by gblakeman**
Typography updates and minor design refresh.

Some screenshots below. Mobile remains largely un-changed.

screen shot on 2016-01-23 at 17-32-55
screen shot on 2016-01-23 at 17-33-34
screen shot on 2016-01-23 at 17-33-56

### CODE REVIEW

**Comment by BergerFohr** [comment]
LGTM

**Comment by BergerFohr** [comment]
Nice work Grant!

**Comment by jayzes** [comment]
LGTM. Shall we :shipit: ?

**Comment by gblakeman** [comment]
:+1:

**Comment by jayzes** [comment]
Done!

**Pull request merged**
